### ISSUE TITLE
Incompatibility with 2023.1

### ISSUE THREAD

**Issue by Tikkle** [MyNameIsAres/MineAcademy-Development#4]
Excuse my ignorance if you are already working on updating.

**ERROR**
```
Plugin 'MineAcademy Development Development' (version '2022.3-1.5.22')
is not compatible with the current version of the IDE, because it requires build 223.*
or older but the current build is IC-231.8109.175
```

**Comment by MyNameIsAres** [comment]
Hi Tikkle! Thanks for the issue. There's an update in the works with reworked features. However, I'll go ahead and update the plugin to the latest version soon so it's compatible.

**Comment by MyNameIsAres** [comment]
Updated the project. See the release here: **https://github.com/MyNameIsAres/MineAcademy-Development/releases/tag/1.0.4-beta**
